TPS.Web/Areas/Administration/Controllers/TravelPackageCitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TPS.Domain;

namespace TPS.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class TravelPackageCitiesController : AdministrationController
    {
        public TravelPackageCitiesController(TPSDbContext db, UserManager<IdentityUser> userManager)
            : base(db, userManager)
        {

        }
        // GET: Administration/TravelPackageCities
        public async Task<IActionResult> Index(int tpId)
        {
            ViewBag.TravelPackage = _db.TravelPackages
                .Include(tp=> tp.Cities)
                .First(tp => tp.Id == tpId);

            var tPSDbContext = _db.TravelPackageCities
                .Include(t => t.City)
                .Include(t => t.TravelPackage)
                .Where(t=>t.TravelPackageId == tpId);   

            return View(await tPSDbContext.ToListAsync());
        }


        // GET: Administration/TravelPackageCities/Create
        public IActionResult Create(int tpId, int? page)
        {
            var pageNumber = page ?? 0;
            if(pageNumber < 0) { pageNumber = 0; } 
            ViewBag.PageNumber = pageNumber;
            int skip = (page ?? 1) * 100;           
            //ViewBag.Cities = _db.Cities.Skip(skip).Take(100).ToList();
            ViewBag.Cities = _db.Cities.OrderBy(c=>c.Name).ToList();
            ViewBag.TravelPackage = _db.TravelPackages.First(tp => tp.Id == tpId); 
            return View();
        }

        // POST: Administration/TravelPackageCities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TravelPackageId,CityId,NumberOfDays")] TravelPackageCity travelPackageCity)
        {
            if (ModelState.IsValid)
            {
                _db.Add(travelPackageCity);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index),new { tpId = travelPackageCity.TravelPackageId });
            }
            ViewData["CityId"] = new SelectList(_db.Cities, "Id", "ASCII", travelPackageCity.CityId);
            ViewData["TravelPackageId"] = new SelectList(_db.TravelPackages, "Id", "Description", travelPackageCity.TravelPackageId);
            return View(travelPackageCity);
        }
    }
}

TPS.Web/Areas/Administration/Controllers/TravelPackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TPS.Domain;
using TPS.Web.Areas.Administration.Models;

namespace TPS.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class TravelPackagesController : AdministrationController
    {
        public TravelPackagesController(TPSDbContext db, UserManager<IdentityUser> userManager)
            :base(db,userManager)
        {
           
        }

        // GET: Administration/TravelPackages
        public async Task<IActionResult> Index()
        {
            return View(await _db.TravelPackages.ToListAsync());
        }

        // GET: Administration/TravelPackages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelPackage = await _db.TravelPackages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (travelPackage == null)
            {
                return NotFound();
            }

            return View(travelPackage);
        }

        // GET: Administration/TravelPackages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Administration/TravelPackages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,StatusId,RRP")] TravelPackage travelPackage)
        {
            if (ModelState.IsValid)
            {
                _db.Add(travelPackage);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(travelPackage);
        }

        // GET: Administration/TravelPackages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelPackage = await _db.TravelPackages
               .Include(tp => tp.Cities)
                   .ThenInclude(tpc => tpc.City)
               .Include(tp => tp.Cities)
                   .ThenInclude(tpc => tpc.TravelPackageCityAttractions)
                   .ThenInclude(tpca => tpca.CityAttraction)
               .FirstOrDefaultAsync(tp => tp.Id == id); 

            if (travelPackage == null)
            {
                return NotFound();
            }
            return View(travelPackage);
        }

        // POST: Administration/TravelPackages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TravelPackage travelPackage)
        {
            if (id != travelPackage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(travelPackage);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TravelPackageExists(travelPackage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { area = "Administration" });
            }
            return View(travelPackage);
        }

        // GET: Administration/TravelPackages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelPackage = await _db.TravelPackages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (travelPackage == null)
            {
                return NotFound();
            }

            return View(travelPackage);
        }

        // POST: Administration/TravelPackages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var travelPackage = await _db.TravelPackages.FindAsync(id);
            _db.TravelPackages.Remove(travelPackage);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TravelPackageExists(int id)
        {
            return _db.TravelPackages.Any(e => e.Id == id);
        }
    }
}

TPS.Web/Controllers/TravelPackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TPS.Domain;
using TPS.Web.Models;

namespace TPS.Web.Controllers
{
    [Route("[controller]/[action]")]
    public class TravelPackagesController : Controller
    {
        private readonly TPSDbContext _context;

        public TravelPackagesController(TPSDbContext context)
        {
            _context = context;
        }

        // GET: TravelPackages
        public async Task<IActionResult> Index()
        {
            return View(await _context.TravelPackages.ToListAsync());
        }

        [HttpGet]
        [Route("{cityName}")]   
        public async Task<IActionResult> SearchByCity(string cityName)
        {
            var result = await _context.TravelPackages
                .Include(tp=>tp.Cities)
                    .ThenInclude(tpc=>tpc.City)
                .Where(tp => tp.Cities.Any(tpc=>tpc.City.Name.Contains(cityName)))
                .ToListAsync();

            return View("Index", result);
        }


        // GET: TravelPackages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var result = await _context.TravelPackages
                .Include(tp => tp.Cities)
                    .ThenInclude(tpc => tpc.City)
                .Include(tp => tp.Cities)
                    .ThenInclude(tpc => tpc.TravelPackageCityAttractions)
                    .ThenInclude(tpca => tpca.CityAttraction)
                .FirstOrDefaultAsync(tp => tp.Id == id);

            if(result == null)
            {
                return NotFound();
            }

            return View(result);
        }

        // GET: Administration/TravelPackages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelPackage = await _context.TravelPackages
               .Include(tp => tp.Cities)
                   .ThenInclude(tpc => tpc.City)
               .Include(tp => tp.Cities)
                   .ThenInclude(tpc => tpc.TravelPackageCityAttractions)
                   .ThenInclude(tpca => tpca.CityAttraction)
               .FirstOrDefaultAsync(tp => tp.Id == id);

            if (travelPackage == null)
            {
                return NotFound();
            }
            return View(travelPackage);
        }

        // POST: Administration/TravelPackages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,StatusId,RRP")] TravelPackage travelPackage)
        {
            if (id != travelPackage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(travelPackage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TravelPackageExists(travelPackage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(travelPackage);
        }


        private bool TravelPackageExists(int id)
        {
            return _context.TravelPackages.Any(e => e.Id == id);
        }
    }
}

TPS.Web/Areas/Administration/Views/TravelPackages/Create.cshtml
@model TPS.Domain.TravelPackage

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>TravelPackage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RRP" class="control-label"></label>
                <input asp-for="RRP" class="form-control" />
                <span asp-validation-for="RRP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-area="Administration" asp-controller="TravelPackages"asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TPS.Web/Areas/Administration/Views/TravelPackages/Delete.cshtml
@model TPS.Domain.TravelPackage

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TravelPackage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RRP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RRP)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-area="Administration" asp-controller="TravelPackages" asp-action="Index">Back to List</a>
    </form>
</div>

TPS.Web/Areas/Administration/Views/TravelPackages/Details.cshtml
@model TPS.Domain.TravelPackage

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TravelPackage</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RRP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RRP)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-area="Administration" asp-controller="TravelPackages" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index" asp-area="Administration" asp-controller="TravelPackages">Back to List</a>
</div>

TPS.Web/Areas/Administration/Views/TravelPackages/Edit.cshtml
@model TPS.Domain.TravelPackage

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TravelPackage</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusId" class="control-label"></label>
                <input asp-for="StatusId" class="form-control" />
                <span asp-validation-for="StatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RRP" class="control-label"></label>
                <input asp-for="RRP" class="form-control" />
                <span asp-validation-for="RRP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a 
       asp-area="Administration"
       asp-controller="TravelPackages"
       asp-action="Index">
    Back to List
    </a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TPS.Web/Areas/Administration/Views/TravelPackages/Index.cshtml
@model IEnumerable<TPS.Domain.TravelPackage>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Intensity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DurationDay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RRP)
            </th>
            <th>
                Cities
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Intensity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DurationDay)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RRP)
            </td>
            <td>
                <a asp-action="Index" asp-controller="TravelPackageCities" asp-route-tpId="@item.Id">Cities</a>
            </td>
            <td>
                <a asp-area="Administration" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-area="Administration" asp-action="Details" asp-route-id="@item.Id">Details</a>
                <a asp-area="Administration" asp-action="Delete" asp-route-id="@item.Id">Delete</a>

            </td>
        </tr>
        }
    </tbody>
</table>