TPS.Web/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TPS.Web.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TPS.Web/Controllers/TravelPackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TPS.Domain;
using TPS.Web.Models;

namespace TPS.Web.Controllers
{
    [Route("[controller]/[action]")]
    public class TravelPackagesController : Controller
    {
        private readonly TPSDbContext _context;

        public TravelPackagesController(TPSDbContext context)
        {
            _context = context;
        }

        // GET: TravelPackages
        public async Task<IActionResult> Index()
        {
            return View(await _context.TravelPackages.ToListAsync());
        }

        [HttpGet]
        [Route("{cityName}")]   
        public async Task<IActionResult> SearchByCity(string cityName)
        {
            var result = await _context.TravelPackages
                .Include(tp=>tp.Cities)
                    .ThenInclude(tpc=>tpc.City)
                .Where(tp => tp.Cities.Any(tpc=>tpc.City.Name.Contains(cityName)))
                .ToListAsync();

            return View("Index", result);
        }


        // GET: TravelPackages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var result = await _context.TravelPackages
                .Include(tp => tp.Cities)
                    .ThenInclude(tpc => tpc.City)
                .Include(tp => tp.Cities)
                    .ThenInclude(tpc => tpc.TravelPackageCityAttractions)
                    .ThenInclude(tpca => tpca.CityAttraction)
                .FirstOrDefaultAsync(tp => tp.Id == id);

            if(result == null)
            {
                return NotFound();
            }

            return View(result);
        }

        // GET: Administration/TravelPackages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var travelPackage = await _context.TravelPackages
               .Include(tp => tp.Cities)
                   .ThenInclude(tpc => tpc.City)
               .Include(tp => tp.Cities)
                   .ThenInclude(tpc => tpc.TravelPackageCityAttractions)
                   .ThenInclude(tpca => tpca.CityAttraction)
               .FirstOrDefaultAsync(tp => tp.Id == id);

            if (travelPackage == null)
            {
                return NotFound();
            }
            return View(travelPackage);
        }

        // POST: Administration/TravelPackages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,StatusId,RRP")] TravelPackage travelPackage)
        {
            if (id != travelPackage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(travelPackage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TravelPackageExists(travelPackage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(travelPackage);
        }


        private bool TravelPackageExists(int id)
        {
            return _context.TravelPackages.Any(e => e.Id == id);
        }
    }
}

TPS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TPS.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TPS.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole("Administrator"))
                        {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="Administration" asp-controller="TravelPackages" asp-action="Index">Packages</a>
                    </li>
                        }
                        @if (User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">My Account</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - TPS.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TPS.Web/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Totally Worth It</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Destino project">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Home -->
    <link rel="stylesheet" type="text/css" href="/styles/bootstrap4/bootstrap.min.css">
    <link href="plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="/plugins/OwlCarousel2-2.2.1/animate.css">
    <link href="plugins/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="/styles/main_styles.css">
    <link rel="stylesheet" type="text/css" href="/styles/responsive.css">
    <!-- About -->
    <link rel="stylesheet" type="text/css" href="/styles/about_styles.css">
    <link rel="stylesheet" type="text/css" href="/styles/about_responsive.css">
    <!-- Packages -->
    <link rel="stylesheet" type="text/css" href="/styles/offers_styles.css">
    <link rel="stylesheet" type="text/css" href="/styles/offers_responsive.css">
    <!-- Login -->
    <link rel="stylesheet" type="text/css" href="styles/contact_styles.css">
    <link rel="stylesheet" type="text/css" href="styles/contact_responsive.css">
</head>
<body>

    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="header_container d-flex flex-row align-items-center justify-content-start">

                        <!-- Logo -->
                        <div class="logo_container">
                            <div class="logo">
                                <div>Totally Worth It</div>
                                <div>travel agency</div>
                                <div class="logo_image">
                                    <img src="~/images/logo.png" alt="">
                                </div>
                            </div>
                        </div>

                        <!-- Main Navigation -->
                        <nav class="main_nav ml-auto">
                            <ul class="main_nav_list">
                                <li class="main_nav_item active">
                                    <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="main_nav_item">
                                    <a asp-area="" asp-controller="TravelPackages" asp-action="Index">Packages</a>
                                </li>
                                <li class="main_nav_item">
                                    <a asp-area="" asp-controller="About" asp-action="Index">About</a>
                                </li>
                                <!-- Partial Login-->
                                @if (User.IsInRole("Administrator"))
                                {
                                    <li class="main_nav_item">
                                        <a asp-area="Administration" asp-controller="TravelPackages" asp-action="Index">Packages</a>
                                    </li>
                                }
                                @if (User.IsInRole("Customer"))
                                {
                                    <li class="main_nav_item">
                                        <a asp-area="Customer" asp-controller="Home" asp-action="Index">My Account</a>
                                    </li>
                                }
                                <partial name="_LoginPartial" />
                            </ul>
                        </nav>

                        <!-- Search -->
                        <div class="search">
                            <form action="#" class="search_form">
                                <input type="search" name="search_input" class="search_input ctrl_class" required="required" placeholder="Keyword">
                                <button type="submit" class="search_button ml-auto ctrl_class"><img src="images/search.png" alt=""></button>
                            </form>
                        </div>

                        <!-- Hamburger -->
                        <div class="hamburger ml-auto">
                            <i class="fa fa-bars" aria-hidden="true"></i>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Menu -->

    <div class="menu_container menu_mm">

        <!-- Menu Close Button -->
        <div class="menu_close_container">
            <div class="menu_close"></div>
        </div>

        <!-- Menu Items -->
        <div class="menu_inner menu_mm">
            <div class="menu menu_mm">
                <div class="menu_search_form_container">
                    <form action="#" id="menu_search_form">
                        <input type="search" class="menu_search_input menu_mm">
                        <button id="menu_search_submit" class="menu_search_submit" type="submit"><img src="images/search_2.png" alt=""></button>
                    </form>
                </div>
                <ul class="menu_list menu_mm">
                    <li class="menu_item menu_mm">
                        <a asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="menu_item menu_mm">
                        <a class="nav-link" asp-controller="About" asp-action="Index">About us</a>
                    </li>
                    <li class="menu_item menu_mm">
                        <a href="offers.html">Offers</a>
                    </li>
                    <li class="menu_item menu_mm">
                        <a href="news.html">News</a>
                    </li>
                    <li class="menu_item menu_mm">
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>

                <!-- Menu Social -->

                <div class="menu_social_container menu_mm">
                    <ul class="menu_social menu_mm">
                        <li class="menu_social_item menu_mm">
                            <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                        </li>
                        <li class="menu_social_item menu_mm">
                            <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                        </li>
                        <li class="menu_social_item menu_mm">
                            <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        </li>
                        <li class="menu_social_item menu_mm">
                            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        </li>
                        <li class="menu_social_item menu_mm">
                            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </div>

    @RenderBody()

    <!-- Footer -->

    <footer class="footer">
        <div class="container">
            <div class="row">

                <!-- Footer Column -->
                <div class="col-lg-12 footer_col">
                    <div class="footer_about">
                        <!-- Logo -->
                        <div class="logo_container">
                            <div class="logo">
                                <div>totally worth it</div>
                                <div>travel agency</div>
                                <div class="logo_image">
                                    <img src="/images/logo.png" alt="">
                                </div>
                            </div>
                        </div>
                        <div class="footer_about_text">All prices are subject to changes</div>
                        <div class="copyright">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved
                        </div>
                    </div>
                </div>

                <!-- Footer Column -->
                <div class="col-lg-4 footer_col">
                    <div class="footer_latest">
                        <div class="footer_title">Latest News</div>
                        <div class="footer_latest_content">

                            <!-- Footer Latest Post -->
                            <div class="footer_latest_item">
                                <div class="footer_latest_image">
                                    <img src="/images/latest_1.jpg" alt="https://unsplash.com/peecho">
                                </div>
                                <div class="footer_latest_item_content">
                                    <div class="footer_latest_item_title">
                                        <a href="#">Amazing Forest</a>
                                    </div>
                                    <div class="footer_latest_item_date">Jan 09, 2018</div>
                                </div>
                            </div>

                            <!-- Footer Latest Post -->
                            <div class="footer_latest_item">
                                <div class="footer_latest_image">
                                    <img src="/images/latest_2.jpg" alt="https://unsplash.com/sanfrancisco">
                                </div>
                                <div class="footer_latest_item_content">
                                    <div class="footer_latest_item_title">
                                        <a href="#">A perfect vacation</a>
                                    </div>
                                    <div class="footer_latest_item_date">Jan 09, 2018</div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <!-- Footer Column -->
                <div class="col-lg-4 footer_col">
                    <div class="tags footer_tags">
                        <div class="footer_title">Tags</div>
                        <ul class="tags_content d-flex flex-row flex-wrap align-items-start justify-content-start">
                            <li class="tag">
                                <a href="#">travel</a>
                            </li>
                            <li class="tag">
                                <a href="#">summer</a>
                            </li>
                            <li class="tag">
                                <a href="#">cruise</a>
                            </li>
                            <li class="tag">
                                <a href="#">beach</a>
                            </li>
                            <li class="tag">
                                <a href="#">offer</a>
                            </li>
                            <li class="tag">
                                <a href="#">vacation</a>
                            </li>
                            <li class="tag">
                                <a href="#">trip</a>
                            </li>
                            <li class="tag">
                                <a href="#">city break</a>
                            </li>
                            <li class="tag">
                                <a href="#">adventure</a>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </footer>

    <script src="/js/jquery-3.2.1.min.js"></script>
    <script src="/styles/bootstrap4/popper.js"></script>
    <script src="/styles/bootstrap4/bootstrap.min.js"></script>
    <script src="/plugins/greensock/TweenMax.min.js"></script>
    <script src="/plugins/greensock/TimelineMax.min.js"></script>
    <script src="/plugins/scrollmagic/ScrollMagic.min.js"></script>
    <script src="/plugins/greensock/animation.gsap.min.js"></script>
    <script src="/plugins/greensock/ScrollToPlugin.min.js"></script>
    <script src="/plugins/easing/easing.js"></script>
    <script src="/plugins/parallax-js-master/parallax.min.js"></script>
    <script src="/js/about_custom.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>