TPS.Web/Areas/Administration/Controllers/TravelPackageCitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TPS.Domain;

namespace TPS.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class TravelPackageCitiesController : AdministrationController
    {
        public TravelPackageCitiesController(TPSDbContext db, UserManager<IdentityUser> userManager)
            : base(db, userManager)
        {

        }
        // GET: Administration/TravelPackageCities
        public async Task<IActionResult> Index(int tpId)
        {
            ViewBag.TravelPackage = _db.TravelPackages
                .Include(tp=> tp.Cities)
                .First(tp => tp.Id == tpId);

            var tPSDbContext = _db.TravelPackageCities
                .Include(t => t.City)
                .Include(t => t.TravelPackage)
                .Where(t=>t.TravelPackageId == tpId);   

            return View(await tPSDbContext.ToListAsync());
        }


        // GET: Administration/TravelPackageCities/Create
        public IActionResult Create(int tpId, int? page)
        {
            var pageNumber = page ?? 0;
            if(pageNumber < 0) { pageNumber = 0; } 
            ViewBag.PageNumber = pageNumber;
            int skip = (page ?? 1) * 100;           
            //ViewBag.Cities = _db.Cities.Skip(skip).Take(100).ToList();
            ViewBag.Cities = _db.Cities.OrderBy(c=>c.Name).ToList();
            ViewBag.TravelPackage = _db.TravelPackages.First(tp => tp.Id == tpId); 
            return View();
        }

        // POST: Administration/TravelPackageCities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TravelPackageId,CityId,NumberOfDays")] TravelPackageCity travelPackageCity)
        {
            if (ModelState.IsValid)
            {
                _db.Add(travelPackageCity);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index),new { tpId = travelPackageCity.TravelPackageId });
            }
            ViewData["CityId"] = new SelectList(_db.Cities, "Id", "ASCII", travelPackageCity.CityId);
            ViewData["TravelPackageId"] = new SelectList(_db.TravelPackages, "Id", "Description", travelPackageCity.TravelPackageId);
            return View(travelPackageCity);
        }
    }
}

TPS.Web/Areas/Administration/Controllers/TravelPackageCityAttractionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TPS.Domain;

namespace TPS.Web.Areas.Administration.Controllers
{
    public class TravelPackageCityAttractionsController : AdministrationController
    {

        public TravelPackageCityAttractionsController(TPSDbContext db, UserManager<IdentityUser> userManager)
          : base(db, userManager)
        {

        }
        //tpcId = travel package city id
        public IActionResult Index(int tpcId)
        {

            ViewBag.City = _db.TravelPackageCities
                .Include(tpc=>tpc.TravelPackage)
                 .Include(tpc => tpc.City)
                .First(tpc => tpc.Id == tpcId); 


            var attractions = _db.TravelPackageCityAttractions
                .Include(tpca => tpca.CityAttraction)
                    .ThenInclude(ca => ca.City)
                .Include(tpca => tpca.TravelPackageCity)
                    .ThenInclude(tpc => tpc.TravelPackage)
                .Where(tpca => tpca.TravelPackageCityId == tpcId)
                .ToList(); 
               
            return View(attractions);
        }
    
        [HttpGet]
        public IActionResult CreateFromList(int tpcId)
        {
           var travelPackageCity = _db.TravelPackageCities
            .Include(tpc => tpc.TravelPackage)
            .Include(tpc => tpc.City)
            .First(tpc => tpc.Id == tpcId);

            ViewBag.TravelPackageCity = travelPackageCity;

            var attractions = _db.CityAttractions
                .Where(ca => ca.CityId == travelPackageCity.CityId)
                .ToList();

            return View(attractions); 
        }


        [HttpPost]
        public IActionResult CreateFromList(TravelPackageCityAttraction m)
        {
            var tpca = new TravelPackageCityAttraction
            {
                 CityAttractionId = m.CityAttractionId,
                 TravelPackageCityId = m.TravelPackageCityId
            };
            _db.TravelPackageCityAttractions.Add(tpca);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index), new { tpcId = m.TravelPackageCityId }); 
        }

        [HttpGet]
        public async Task<IActionResult> Create(int cityId)
        {
            var ca = _db.CityAttractions
                .First(ca => ca.City.Id == cityId);

            return View(ca);
        }       

        [HttpPost]
        public async Task<IActionResult> Create(TravelPackageCityAttraction model)
        {
            if (ModelState.IsValid)
            {
                var tpca = new TravelPackageCityAttraction
                {
                    CityAttractionId = model.CityAttractionId,
                    TravelPackageCityId = model.TravelPackageCityId
                };
                _db.TravelPackageCityAttractions.Add(tpca);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index), new { tpcId = model.TravelPackageCityId});
            }
            return View(model);
        }

        public async Task<IActionResult> Remove(int? id)
        {
            var tpca = await _db.TravelPackageCityAttractions.FindAsync(id);
            _db.TravelPackageCityAttractions.Remove(tpca);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { tpcId = tpca.TravelPackageCityId });
        }
    }
}

TPS.Web/Areas/Administration/Views/TravelPackageCities/Create.cshtml
@{
    ViewData["Title"] = "Create";
    var tp = (TPS.Domain.TravelPackage)ViewBag.TravelPackage;
    var cities = (List<TPS.Domain.City>)ViewBag.Cities;
    var page = (int)ViewBag.PageNumber;
}

<h1>@tp.Name (Add City)</h1>    

@foreach (var c in cities)
{  
    <form asp-action="Create">
        <div style="padding:2.5px;border:1px solid black;margin:1.5px;">
             @c.Name (@c.Country) 
             Days: <input type="text"name="NumberOfDays" />
            <input type="hidden" name="TravelPackageId" value="@tp.Id" />
            <input type="hidden" name="CityId" value="@c.Id" />
            <input type="submit" value="Add" />
        </div>               
    </form>      
        }
@if (page > 0)
{
    <a asp-action="Create" asp-route-tpid="@tp.Id" asp-route-page="@(page + 1)">Previous</a>
}
<a asp-action="Create" asp-route-tpid="@tp.Id" asp-route-page="@(page + 1)">Next</a>

TPS.Web/Areas/Administration/Views/TravelPackageCities/Index.cshtml
@model IEnumerable<TPS.Domain.TravelPackageCity>

@{
    ViewData["Title"] = "Index";
    var tp = (TPS.Domain.TravelPackage)ViewBag.TravelPackage;
}

<h2>Travel Package: @tp.Name</h2>

<p>
    <a asp-action="Create" asp-route-tpId="@tp.Id">Add City</a>
</p>
<table class="table">
    <thead>
        <tr class="row">
            <th class="col-3">City</th>
            <th class="col-1">Days</th>
            <th class="col-8">Attractions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="row">
                <td class="col-3">@item.City.Name</td>
                <td class="col-1">@item.NumberOfDays</td>
                @foreach (var item1 in item.TravelPackageCityAttractions)
                {
                    <td class="col-8">
                        <p>@item1.CityAttraction.CityName</p>
                    </td>
                }
                <td><a asp-action="Index" asp-controller="TravelPackageCityAttractions" asp-route-tpcId="@item.Id">Attractions</a></td>
            </tr>
        }
    </tbody>
</table>